#!/bin/sh
GREP=${GREP:-grep}
# Moderately long lines
ll="foo "
for x in 1 2 3 4 5 6 7 8 9 10 11 12
do
  ll="$ll$ll"
done
res=$(echo $ll | $GREP bar 2>&1)
case $res in
  ('') ;;
  (*) exit 9;;
esac
printf '%s\n' "$0 passed"
exit 0
